title: '@cullaloe | Tech, tales and imagery'
description: '@cullaloe'
analytics: UA-29333042-8 # Google Analytics
show_downloads: true
# theme: jekyll-theme-minimal

# Build Settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jemoji
  # - jekyll-feed - replaced with feed.xml template
  - jekyll-sitemap


permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cullaloe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nick Hood # add your name
author-img: nick-hood.jpg # add your photo
about-author: Tech, tales and imagery # add description
about-page: about
social-twitter: cullaloe # add your Twitter handle
social-facebook: cullaloe # add your Facebook handle
social-github: cullaloe # add your Github handle
social-linkedin: cullaloe # add your Linkedin handle
social-email: nick@cullaloe.net # add your Email address

# Disqus
discus-identifier: cullaloe-gh # add your discus identifier

paginate: 10
paginate_path: "/page/:num"
