title: 'Tech, tales and imagery'
description: 'A technical blog'
analytics: UA-29333042-8 # Google Analytics
show_downloads: true
# theme: jekyll-theme-minimal

# Build Settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jemoji
  # - jekyll-feed - replaced with feed.xml template
  - jekyll-sitemap
  - jekyll-scholar

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cullaloe.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: cullaloe #if your site has a twitter account, enter it here

scholar:
  style: apa
  locale: en

  source: /Users/nickhood/Dropbox/Bibliographies
  bibliography: library.bib

  query: "@*"

# Author Settings
author: Nick Hood # add your name
author-img: nick-hood.jpg # add your photo
about-author: Tech, tales and imagery # add description
about-page: about
social-twitter: NixImagery # add your Twitter handle
social-orcid: 0000-0001-7891-9736
social-facebook: NixImagery # add your Facebook handle
social-github: NixImagery # add your Github handle
social-instagram: NixImagery # add your Insta handle
social-email: nick@cullaloe.com # add your Email address

# Disqus
discus-identifier: cullaloe-gh # add your discus identifier

paginate: 10
paginate_path: "/page/:num"
