project:
  type: website
  output-dir: docs
  preview:
      port: 4001

website:
  title: "NixImagery.github.io"
  site-url: https://NixImagery.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
