project:
  type: website
  output-dir: docs
  preview:
      port: 4001

website:
  title: "NixImagery.github.io"
  site-url: https://NixImagery.github.io
  search: false
  favicon: favicon.ico
  page-footer: 
    left: 
      - text: Copyright &copy; Nick Hood
  navbar:
    right:
      - icon: github
        href: https://github.com/NixImagery
      - icon: instagram
        href: https://www.instagram.com/niximagery/
      - icon: twitter
        href: https://twitter.com/NixImagery
  google-analytics: G-HRRCR9KGPW

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
